language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

# command to run tests
script:
  - nosetests

after_success:
  - bash <(coveralls)
  - CODECLIMATE_REPO_TOKEN=a7ccef8ae2a502a4d8f38fbfa42baee941b05e0b285ebb5db5fd5ae740a14046 codeclimate-test-reporter


