language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

# command to run tests
script:
  - nosetests
  - coverage run main.py
after_success:
  coveralls

